string=input("Enter a string : ")
print("(a) The total number of characters in the string :",len(string))
print("(b) The string repeated 10 times:",string*10)
print("(c) The first character of the string (remember that string indices start at 0):",string[0:len(string)])
print("(d) The first three characters of the string: ",string[:3])
print("(e) The last three characters of the string: ",string[-3:])
print("(f) The string backwards", string[::-1])
print("(g) Is there seventh charater: " , end =" ")
if (len(string) == 7): print("YES")
else : print("NO")
print("(h)The string with its first and last characters removed: ", string[1:len(string)])
print("(i) The string in all caps ", string.upper())
print("(j) The string with every a replaced with an e", string.replace("a", "e"))